{% set name = "compas_viewer" %}
{% set version = "1.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8812f106bfeb7e08d00109dce4e6f7ed3ff030c96a4ed088b6bb3d8ef37e7ab2

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - compas >=2.2
    - freetype-py
    - pyopengl
    - pyside6

test:
  requires:
    - python {{ python_min }}
  imports:
    - compas_viewer

about:
  home: https://compas.dev/compas_viewer/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Viewer for COMPAS 2 based on PyOpenGL and PyQt6.'
  doc_url: https://compas.dev/compas_viewer/
  dev_url: https://github.com/compas-dev/compas_viewer

extra:
  recipe-maintainers:
    - tomvanmele
    - Licini
